name: andre's personal website

markdown: kramdown
highlighter: rouge

permalink: /blog/:year/:month/:day/:title

footer-links:
    github: andre-1337
    email: andremont0101@gmail.com

kramdown:
  input: GFM
  syntax_highlighter_opts:
    default_lang: html
    css_class: 'syntax'

plugins:
  - jekyll-feed